import { FieldCheckbox, FieldDateTime, FieldLookup, FieldMultiText, FieldText, FieldInteger } from "eos-webui-formgen";

export interface IARCFields {
    ISN_CLS: FieldText.IText
    IND_CLS: FieldLookup.ILookup,/*-*/IND_ORD: FieldText.IText,
    START_YEAR: FieldDateTime.IDateTime,
    END_YEAR: FieldDateTime.IDateTime,
    ISN_TYPE_DOCUM: FieldLookup.ILookup,
    E_DOCUMENT: FieldCheckbox.ICheckbox
    ISN_KEEP_CLAUSE: FieldLookup.ILookup,
    ISN_KEEP_PERIOD: FieldLookup.ILookup,
    NAME: FieldMultiText.IMultiText,
    VOLUME_NUM: FieldInteger.IInteger,
    PART_NUM: FieldInteger.IInteger,
    SHEET_COUNT: FieldInteger.IInteger,
    FILESIZE: FieldInteger.IInteger,
    ISN_SECURLEVEL: FieldLookup.ILookup,
    ARCHIVAL_CODE: FieldText.IText,
    MIN_DOC_DATE: FieldDateTime.IDateTime,
    MAX_DOC_DATE: FieldDateTime.IDateTime,
    KEEP_BEFORE: FieldDateTime.IDateTime,
    DESTROY_DATE: FieldDateTime.IDateTime,
    HAS_RESERVE_FUND: FieldCheckbox.ICheckbox,
    NOTE: FieldMultiText.IMultiText,
    //вторая вкладка
    ISN_INVENTORY: FieldText.IText,
    INVENTORY_NUM1: FieldText.IText,
    ISN_SUMINVENTORY: FieldText.IText,
    SUMINVENTORY_NUM: FieldText.IText,
    SUMINVENTORY_NUM2: FieldText.IText,
    ISN_ACT: FieldText.IText,
    ARH_ACT_ACT_DATE: FieldDateTime.IDateTime,
    ARH_ACT_TYPE_NAME: FieldText.IText,
    //третья
    ISN_LOCATION: FieldLookup.ILookup,
    //ARH_UNIT_FEATURE = "ARH_UNIT_FEATURE", //Справочник особенностей, пока не используется.
}
export enum Fields {
    IND_CLS = "IND_CLS",
    IND_ORD = "IND_ORD",
    START_YEAR = "START_YEAR",
    END_YEAR = "END_YEAR",
    ISN_TYPE_DOCUM = "ISN_TYPE_DOCUM",
    E_DOCUMENT = "E_DOCUMENT",
    ISN_KEEP_CLAUSE = "ISN_KEEP_CLAUSE",
    ISN_KEEP_PERIOD = "ISN_KEEP_PERIOD",
    NAME = "NAME",
    VOLUME_NUM = "VOLUME_NUM",
    PART_NUM = "PART_NUM",
    SHEET_COUNT = "SHEET_COUNT",
    ISN_SECURLEVEL = "ISN_SECURLEVEL",
    MIN_DOC_DATE = "MIN_DOC_DATE",
    MAX_DOC_DATE = "MAX_DOC_DATE",
    KEEP_BEFORE = "KEEP_BEFORE",
    ARH_UNIT_FEATURE = "ARH_UNIT_FEATURE",
    NOTE = "NOTE",
    ISN_INVENTORY = "ISN_INVENTORY",
    INVENTORY_NUM1 = "INVENTORY_NUM1",
    ISN_SUMINVENTORY = "ISN_SUMINVENTORY",
    SUMINVENTORY_NUM = "SUMINVENTORY_NUM",
    SUMINVENTORY_NUM2 = "SUMINVENTORY_NUM2",
    ARCHIVAL_CODE = "ARCHIVAL_CODE",
    ISN_LOCATION = "ISN_LOCATION",
    ISN_ACT = "ISN_ACT",
    ARH_ACT_ACT_DATE = "ARH_ACT_ACT_DATE",
    ARH_ACT_TYPE_NAME = "ARH_ACT_TYPE_NAME",
    ISN_CLS = "ISN_CLS",
    FILESIZE = "FILESIZE",
    DESTROY_DATE = "DESTROY_DATE",
    HAS_RESERVE_FUND = "HAS_RESERVE_FUND",
}
export default Fields;